### ISSUE TITLE
Cloudinary version not updated

### ISSUE THREAD

**Issue by eybarta** [copleykj/socialize-cloudinary#3]
Hi,

I'm trying to use your plugin in my Meteor app, but getting an error:
- cloudinary@1.14.0 installed, cloudinary@1.13.x needed

My question is, are you still maintaining this package? will it be updated anytime
soon to support the latest Cloudinary package or do I need to downgrade?

thx alot

**Comment by copleykj** [comment]
Thanks for the report. Should be all set now.
