### ISSUE TITLE
Exception while invoking method 'cloudinary.get_download_url' TypeError: ops.filter is not a function

### ISSUE THREAD

**Issue by matikucharski** [copleykj/socialize-cloudinary#5]
I got following error when calling`Cloudinary.downloadUrl` method.
I can see problem is here in server.js file: 
`return Cloudinary.utils.private_download_url(publicId, format, ops.filter(op => op !== 'format'));`

I don't know why it assumes there is filter method in ops object.
What is more it looks like it is bad rewrite of following code `_.omit(ops,"format")` from lepozepo original source code. `filter` is prototype method of Array - not Object

**Comment by copleykj** [comment]
Thanks! I've got some releases to do in the next day or so and I'll get a patch out for this as well.
