### ISSUE TITLE
Cloudinary version warning

### ISSUE THREAD

**Issue by carlosalvidrez** [copleykj/socialize-cloudinary#6]
Hi @copleykj !
First, thank you for sharing your work!

Wanted to let you know I get this warning when launching my app after having installed this meteor package and its underlying dependencies. It seems to me like refreshing the dependency version, or adding some sort of range to it may fix it. 

Here it is:

`
W20210716-20:40:20.798(-4)? (STDERR) WARNING: npm peer requirements (for socialize:cloudinary) not installed:
W20210716-20:40:20.799(-4)? (STDERR)    - cloudinary@1.26.2 installed, cloudinary@1.22.x needed
W20210716-20:40:20.799(-4)? (STDERR)
W20210716-20:40:20.799(-4)? (STDERR)   Read more about installing npm peer dependencies:
W20210716-20:40:20.799(-4)? (STDERR)     http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20210716-20:40:20.799(-4)? (STDERR)`

**Comment by copleykj** [comment]
Thanks for the report. Since these are just peer dependency warnings, it *shouldn't* affect anything. I'll make updated and release a patch later tonight.

**Comment by carlosalvidrez** [comment]
Thanks!!

**Comment by copleykj** [comment]
This should be all set.

**Comment by carlosalvidrez** [comment]
Yes, that worked, thanks @copleykj !
