### ISSUE TITLE
implement with meteor + vue 3

### ISSUE THREAD

**Issue by u-sour** [copleykj/socialize-cloudinary#9]
Hi @copleykj, i'm trying to implement this package with **meteor + vue 3** and i can't find any docs or demo example project how to implement it. can you share any docs or demo related this ? 
thank in advance.

**Comment by copleykj** [comment]
So at the moment nothing outside the readme exists and for the most part I think it's relatively straight forward to implement.

The url-gen library is frontend agnostic, but the Vue integration may be of interest https://cloudinary.com/documentation/vue_integration

**Comment by u-sour** [comment]
@copleykj thank you for info.

**Comment by copleykj** [comment]
You are very welcome.
